-- =============================================================================
-- Green Land · seed inicial de Propiedades y Promociones desde la landing
-- Generado por scripts/generar-seed-landing.js
-- Idempotente: usa el campo `codigo` (GL-LOT-{id}) y `titulo` como llave de
-- inserción. Si la fila ya existe (matchea codigo), no la duplica.
-- =============================================================================

DO $do$
DECLARE
  v_empresa uuid;
BEGIN
  -- Resuelve la empresa: la única del schema (mono-tenant Green Land).
  SELECT id INTO v_empresa FROM greenlanderp.empresas LIMIT 1;
  IF v_empresa IS NULL THEN RAISE EXCEPTION 'No hay empresa en greenlanderp.empresas'; END IF;

  -- ---------------- PROPIEDADES ----------------
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-1', 'Mz. A · Lote 1', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 77000000, 'PYG', 362, 'Credito', 12, 4000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":28.29,"linda":"LOTE 24","calle":"LAPACHO"},"sur":{"m":28.29,"linda":null,"calle":"TIMBO"},"este":{"m":12.8,"linda":null,"calle":"LAPACHO"},"oeste":{"m":12.8,"linda":"LOTE 2","calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-1');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-2', 'Mz. A · Lote 2', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 12, 4000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":28.29,"linda":"1","calle":null},"sur":{"m":28.29,"linda":null,"calle":"TIMBO"},"este":{"m":12.8,"linda":"1","calle":null},"oeste":{"m":12.8,"linda":"3","calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-2');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-3', 'Mz. A · Lote 3', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":28.29,"linda":"2","calle":null},"sur":{"m":28.29,"linda":"4","calle":null},"este":{"m":12.8,"linda":null,"calle":"TIMBO"},"oeste":{"m":12.8,"linda":"6 Y 24","calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-3');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-4', 'Mz. A · Lote 4', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DIFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-4');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-5', 'Mz. A · Lote 5', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-5');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-6', 'Mz. A · Lote 6', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-6');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-7', 'Mz. A · Lote 7', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-7');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-8', 'Mz. A · Lote 8', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-8');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-9', 'Mz. A · Lote 9', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-9');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-10', 'Mz. A · Lote 10', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-10');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-11', 'Mz. A · Lote 11', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-11');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-12', 'Mz. A · Lote 12', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 100000000, 'PYG', 362, 'Credito', 12, 1000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-12');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-13', 'Mz. A · Lote 13', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 170000000, 'PYG', 362, 'Credito', 12, 2000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-13');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-14', 'Mz. A · Lote 14', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 150000000, 'PYG', 362, 'Credito', 12, 2000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-14');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-15', 'Mz. A · Lote 15', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 135418000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-15');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-16', 'Mz. A · Lote 16', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 135418000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-16');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-17', 'Mz. A · Lote 17', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 135418000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-17');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-18', 'Mz. A · Lote 18', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 130, 1399000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-18');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-19', 'Mz. A · Lote 19', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-19');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-20', 'Mz. A · Lote 20', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 130, 1399000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-20');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-21', 'Mz. A · Lote 21', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-21');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-22', 'Mz. A · Lote 22', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-22');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-23', 'Mz. A · Lote 23', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-23');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-24', 'Mz. A · Lote 24', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-24');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-25', 'Mz. B · Lote 1', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 77000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-25');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-26', 'Mz. B · Lote 2', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 65000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-26');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-27', 'Mz. B · Lote 3', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 67925000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-27');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-28', 'Mz. B · Lote 4', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-28');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-29', 'Mz. B · Lote 5', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-29');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-30', 'Mz. B · Lote 6', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-30');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-31', 'Mz. B · Lote 7', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDEQ', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-31');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-32', 'Mz. B · Lote 8', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-32');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-33', 'Mz. B · Lote 9', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-33');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-34', 'Mz. B · Lote 10', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-34');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-35', 'Mz. B · Lote 11', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 40000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-35');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-36', 'Mz. B · Lote 12', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 40000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-36');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-37', 'Mz. B · Lote 13', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-37');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-38', 'Mz. B · Lote 14', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-38');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-39', 'Mz. B · Lote 15', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 55000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-39');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-40', 'Mz. B · Lote 16', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 55000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-40');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-41', 'Mz. B · Lote 17', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 55000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-41');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-42', 'Mz. B · Lote 18', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 40000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-42');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-43', 'Mz. B · Lote 19', 'terreno', 'venta', 'vendida', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 40000000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-43');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-44', 'Mz. B · Lote 20', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 40000000, 'PYG', 362, 'Credito', 1, 5000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-44');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-45', 'Mz. B · Lote 22', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 130, 1000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-45');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-46', 'Mz. B · Lote 21', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 12, 1000000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-46');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-47', 'Mz. B · Lote 23', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 139, 910000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-47');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-48', 'Mz. B · Lote 24', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 36, 1628163, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-48');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-49', 'Mz. C · Lote 1', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-49');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-50', 'Mz. C · Lote 2', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-50');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-51', 'Mz. C · Lote 3', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-51');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-52', 'Mz. C · Lote 4', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-52');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-53', 'Mz. C · Lote 5', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-53');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-54', 'Mz. C · Lote 6', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 12, 5958333, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-54');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-55', 'Mz. C · Lote 7', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-55');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-56', 'Mz. C · Lote 8', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 128818000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-56');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-57', 'Mz. C · Lote 9', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 12, 5958333, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-57');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-58', 'Mz. C · Lote 10', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 362, 'Credito', 12, 5958333, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-58');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-59', 'Mz. C · Lote 11', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-59');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-60', 'Mz. C · Lote 12', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-60');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-61', 'Mz. D · Lote 1', 'terreno', 'venta', 'reservada', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 71500000, 'PYG', 419.5, 'Credito', 130, 1299000, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":13.79,"linda":null,"calle":"LAPACHO"},"sur":{"m":16.61,"linda":"LOTE 2","calle":null},"este":{"m":28.18,"linda":null,"calle":"7"},"oeste":{"m":28.3,"linda":"LOTE 12","calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-61');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-62', 'Mz. D · Lote 2', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 115418000, 'PYG', 412.48, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":34.23,"linda":null,"calle":"LAPACHO"},"sur":{"m":35.24,"linda":"LOTE 3","calle":null},"este":{"m":11.85,"linda":null,"calle":"7"},"oeste":{"m":11.9,"linda":"LOTE 8","calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-62');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-63', 'Mz. D · Lote 3', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 115418000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DEFINIR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-63');
  INSERT INTO greenlanderp.propiedades (empresa_id, codigo, titulo, tipo, operacion, estado, ciudad, barrio, precio, moneda, terreno_m2, modalidad, cuotas_cantidad, cuota_monto, servicios, medidas, finca, padron, cuenta_catastral, destacada, visible_web, activo)
  SELECT v_empresa, 'GL-LOT-64', 'Mz. D · Lote 4', 'terreno', 'venta', 'disponible', 'LAS LOMAS COUNTRY', 'LOMA GRANDE', 122218000, 'PYG', 362, 'Contado', NULL, NULL, '["Agua potable","Energía eléctrica","Calle","Seguridad 24h","Amojonado","Limpio"]'::jsonb, '{"norte":{"m":null,"linda":null,"calle":null},"sur":{"m":null,"linda":null,"calle":null},"este":{"m":null,"linda":null,"calle":null},"oeste":{"m":null,"linda":null,"calle":null}}'::jsonb, '1752', '1798', 'A DESIGNAR', false, true, true
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.propiedades WHERE empresa_id = v_empresa AND codigo = 'GL-LOT-64');

  -- ---------------- PROMOCIONES ----------------
  INSERT INTO greenlanderp.promociones (empresa_id, titulo, descripcion, banner_url, badge, valida_hasta, cta_label, orden, activo, destacada)
  SELECT v_empresa, 'Plan ECO', 'Plan ECO desde Gs. 1.000.000 con refuerzos y Gs. 1.450.000 sin refuerzos. Posesión inmediata.', 'https://greenlandpy.com/assets/images/promo-plan-eco.jpg', '30%', '2026-12-31'::date, 'Quiero esta promoción', 1, true, false
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.promociones WHERE empresa_id = v_empresa AND titulo = 'Plan ECO');
  INSERT INTO greenlanderp.promociones (empresa_id, titulo, descripcion, banner_url, badge, valida_hasta, cta_label, orden, activo, destacada)
  SELECT v_empresa, 'Con la Cooperativa Universitaria 30%', '¡Atención Socios de la Universitaria! Su próxima gran inversión tiene un 30% de descuento exclusivo.', 'https://greenlandpy.com/assets/images/promo-cooperativa.png', '30%', '2026-12-31'::date, 'Quiero esta promoción', 2, true, false
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.promociones WHERE empresa_id = v_empresa AND titulo = 'Con la Cooperativa Universitaria 30%');
  INSERT INTO greenlanderp.promociones (empresa_id, titulo, descripcion, banner_url, badge, valida_hasta, cta_label, orden, activo, destacada)
  SELECT v_empresa, 'Invertí donde la calidad de vida crece', 'En Las Lomas Country asegurás tu lote en barrio cerrado en Loma Grande, con transferencia inmediata por Gs. 80.000.000.', 'https://greenlandpy.com/assets/images/promo-las-lomas.png', 'BARRIO CERRADO', '2026-12-31'::date, 'Quiero esta promoción', 3, true, false
  WHERE NOT EXISTS (SELECT 1 FROM greenlanderp.promociones WHERE empresa_id = v_empresa AND titulo = 'Invertí donde la calidad de vida crece');

END;
$do$;

SELECT pg_notify('pgrst', 'reload schema');
